export const LOCAL_STORAGE_KEYS ={
    OPEN_TABS_IDS: "OPEN_TABS_IDS_KEY",
    TABS_ACCESS_HISTORY: "TABS_ACCESS_HISTORY",
    EMAILS_PAGE_PREFIX: "EMAILS_PAGE_CACHE",
    EMAILS_META_PREFIX: "EMAILS_META_CACHE",
    THEME_MODE_STORAGE_KEY: "THEME_MODE_STORAGE_KEY",
}